services:
  autoblivegift:
    build:
      context: .
      dockerfile: Dockerfile 
    container_name: autoblivegift
    volumes:
      - ./data/data.db:/app/data/data.db
      - ./config.toml:/app/config.toml
      - ./src:/app/src
      - /home/merlin/FlashBot2/cache/nonebot_plugin_bilichat/bili_grpc_auth.json:/app/cookies.json
    restart: unless-stopped