services:
  autoblivegift:
    build:
      context: .
      dockerfile: Dockerfile 
    container_name: autoblivegift
    volumes:
      - ./data/data.db:/app/data/data.db
      - ./config.toml:/app/config.toml
      - ./src:/app/src
    restart: unless-stopped