services:
  autoblivegift:
    build:
      context: .
      dockerfile: Dockerfile 
    container_name: autoblivegift
    volumes:
      - ./data.db:/app/data.db
      - ./cookies.json:/app/cookies.json
      - ./config.yaml:/app/config.yaml
      - ./src:/app/src
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s